(()=>{'use strict';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],recipes=window.TM_RECIPES||[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normal=s=>String(s).replace(/\s/g,'').replace(/계란/g,'달걀').replace(/익힌꼬막살|꼬막살/g,'꼬막').replace(/익힌고구마/g,'고구마').replace(/진간장/g,'간장').replace(/깨소금/g,'깨');
function read(key,fallback){try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch(e){return fallback}}
let timer;function notice(s){const n=$('#notice');if(!n)return;n.textContent=s;n.classList.add('on');clearTimeout(timer);timer=setTimeout(()=>n.classList.remove('on'),2500)}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(e){notice('저장이 제한되어 현재 화면에서만 보관됩니다.');return false}}
const BASIC=[['onion','양파 썰기의 기본'],['scallion','쪽파 다듬고 씻기'],['cockle','꼬막 손질 시작하기'],['green-onion-storage','남은 대파 보관하기'],['meat-tools','고기 손질 전 준비']];
const saveKey='todaymeal-cooking-saved-v1';let stored=read(saveKey,[]);let saved=new Set(Array.isArray(stored)?stored.filter(x=>typeof x==='string'):[]);
const legacy=read('todaymeal-learning-saved-v1',[]);if(Array.isArray(legacy)){legacy.forEach(id=>{if(BASIC.some(b=>b[0]===id))saved.add('basic:'+id)});if(legacy.length){if(write(saveKey,[...saved]))write('todaymeal-learning-saved-v1',[])}}
const icon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h12v18l-6-4-6 4z"/></svg>';
function keyFor(button){return button.closest('#basics')?'basic:'+button.dataset.save:button.dataset.save}
function refreshSaves(){all('[data-save]').forEach(b=>{const on=saved.has(keyFor(b));b.setAttribute('aria-pressed',String(on));const span=b.querySelector('span');if(span)span.textContent=on?'저장됨':'저장하기';});}
function recipeUrl(r){return r.external?'/r/'+encodeURIComponent(r.sourceId):'/recipes/'+r.id+'.html'}
function photo(r){if(r.image)return '<div class="food-photo '+esc(r.image)+'" role="img" aria-label="'+esc(r.title)+' 예시"></div>';if(r.photo&&/^https:\/\//.test(r.photo))return '<img class="food-photo" src="'+esc(r.photo)+'" alt="'+esc(r.title)+'" loading="lazy">';if(r.video)return '<img class="food-photo" src="https://i.ytimg.com/vi/'+r.video.id+'/hqdefault.jpg" alt="'+esc(r.title)+'" loading="lazy">';return '<div class="food-photo no-photo"><span>함께 만드는 한 끼</span><b>'+esc(r.title)+'</b></div>'}
function savedPage(){const target=$('#saved-content');if(!target)return;let html='';saved.forEach(id=>{const r=recipes.find(x=>x.id===id);if(r){html+='<article class="card"><a href="'+recipeUrl(r)+'">'+photo(r)+'</a><div class="copy"><h3>'+esc(r.title)+'</h3><p>조리 약 '+r.time+'분</p><div class="card-actions"><a href="'+recipeUrl(r)+'">레시피 보기 →</a>'+(r.video?'<a href="/classes/'+r.id+'.html">영상 수업 →</a>':'')+'<button class="save-button" data-save="'+r.id+'" aria-pressed="true">'+icon+'<span>저장됨</span></button></div></div></article>';}else if(id.startsWith('basic:')){const i=BASIC.findIndex(b=>'basic:'+b[0]===id);if(i<0)return;html+='<article class="card"><a class="photo '+(i===4?'meat-placeholder':'tile t'+i)+'" href="/learn/'+BASIC[i][0]+'.html" aria-label="'+BASIC[i][1]+' 읽기"></a><div class="copy"><h3>'+BASIC[i][1]+'</h3><div class="card-actions"><a href="/learn/'+BASIC[i][0]+'.html">손질법 보기 →</a><button class="save-button" data-save="'+id+'">'+icon+'<span>저장됨</span></button></div></div></article>';}});target.innerHTML=html;$('#saved-empty').hidden=!!html;refreshSaves()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-save]');if(!b)return;const id=keyFor(b);if(saved.has(id))saved.delete(id);else saved.add(id);write(saveKey,[...saved]);refreshSaves();savedPage();renderBasics();});
// Kids discovery: search across names AND ingredient lists.
let mode='불 없이';function renderKids(){if(!$('#kids-cards'))return;const q=normal($('#kids-search').value);let count=0;all('#kids-cards [data-recipe]').forEach(c=>{const r=recipes.find(x=>x.id===c.dataset.recipe);const show=(mode==='전체'||r.mode===mode)&&normal(r.title+' '+r.ingredients.map(x=>x.name).join(' ')).includes(q);c.hidden=!show;if(show)count++;});$('#kids-count').textContent=count+'개의 요리 · 조리 시간은 예상치예요';$('#kids-empty').hidden=count>0;}
all('[data-mode-filter]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.modeFilter;all('[data-mode-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderKids()}));$('#kids-search')?.addEventListener('input',renderKids);
// Basic preparation filters and tabbed videos.
let category='전체',onlySaved=false;function renderBasics(){if(!$('#basics'))return;const q=normal($('#search').value);let count=0;all('#basics .card').forEach(c=>{const id='basic:'+c.querySelector('[data-save]').dataset.save;const show=(category==='전체'||category===c.dataset.category)&&(!onlySaved||saved.has(id))&&normal(c.textContent+c.dataset.keywords).includes(q);c.hidden=!show;if(show)count++;});$('#count').textContent=count+'개의 손질법';$('#empty').hidden=count>0;}
$('#search')?.addEventListener('input',renderBasics);all('[data-filter]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter;all('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderBasics()}));$('#saved-only')?.addEventListener('click',()=>{onlySaved=!onlySaved;$('#saved-only').setAttribute('aria-pressed',String(onlySaved));renderBasics()});
const tabs=all('[role=tab]');function switchTab(tab){tabs.forEach(t=>{const active=t===tab;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!active;});}tabs.forEach(tab=>{tab.addEventListener('click',()=>switchTab(tab));tab.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?tabs[0]:e.key==='End'?tabs.at(-1):tabs[1-tabs.indexOf(tab)];switchTab(next);next.focus()})});if(location.hash==='#videos'&&$('#tab-video'))switchTab($('#tab-video'));
// Videos load only after explicit play; recipe and steps remain readable without playback.
all('[data-play]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.play;if(!['FglBXmyjdhc','eIo2BaE6LxI'].includes(id))return;const frame=document.createElement('iframe');frame.src='https://www.youtube-nocookie.com/embed/'+id+'?autoplay=1';frame.title=document.querySelector('h1')?.textContent||'요리 영상';frame.allow='autoplay; encrypted-media; picture-in-picture';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';b.parentElement.replaceChildren(frame)}));
// Ingredient matching has no AI guesswork: compare named ingredients, show missing ones.
function rankRecipes(list,selected,pantry,kids){const have=new Set([...selected,...pantry].map(normal));const wanted=[...selected].map(normal);return list.filter(r=>!kids||(!r.external&&r.id!=='cockle-salad')).map(r=>{const names=r.ingredients.map(x=>normal(x.name));const used=wanted.filter(x=>names.includes(x));return {r,used,unused:wanted.filter(x=>!names.includes(x)),missing:r.ingredients.filter(x=>!have.has(normal(x.name)))};}).filter(x=>x.used.length).sort((a,b)=>b.used.length-a.used.length||a.missing.length-b.missing.length);}
window.TMCookingCore={normal,rankRecipes};
let selectedRaw=read('todaymeal-selected-ingredients-v1',[]);let selected=new Set(Array.isArray(selectedRaw)?selectedRaw.filter(x=>typeof x==='string').slice(0,40):[]);let pantry=new Set();let catalog=[...recipes],lastResults=[];
const memoRaw=read('todaymeal-cooking-shopping-v1',[]);let memo=Array.isArray(memoRaw)?memoRaw.filter(x=>x&&typeof x.name==='string').map(x=>({name:x.name,purchased:!!x.purchased})):[];
function paintSelected(){if(!$('#selected-ingredients'))return;$('#selected-ingredients').innerHTML=[...selected].map(n=>'<button data-remove="'+esc(n)+'" aria-label="'+esc(n)+' 선택 취소">'+esc(n)+' ×</button>').join('')||'<p class="note">위 재료를 누르거나 직접 입력해 주세요.</p>';write('todaymeal-selected-ingredients-v1',[...selected])}
function addIngredient(value){value.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean).slice(0,40).forEach(n=>{if(selected.size<40)selected.add(n.slice(0,40))});paintSelected()}
function recommend(){if(!$('#recommend-results'))return;const output=$('#recommend-results');if(!selected.size){output.innerHTML='';$('#recommend-status').textContent='먼저 재료를 하나 이상 골라주세요.';return;}lastResults=rankRecipes(catalog,selected,pantry,$('#kids-only').checked);$('#recommend-status').textContent=lastResults.length+'개의 메뉴 · 선택 재료를 많이 활용하고 추가 재료가 적은 순서입니다.';output.innerHTML=lastResults.map((x,i)=>'<article class="card">'+photo(x.r)+'<div class="copy"><h3>'+esc(x.r.title)+'</h3><p class="tag">선택 재료 '+x.used.length+'/'+selected.size+'개 활용</p><p><b>추가 재료 '+x.missing.length+'개</b><br>'+esc(x.missing.map(z=>z.name).join(', ')||'선택한 재료와 양념으로 준비할 수 있어요.')+'</p>'+(x.unused.length?'<p class="note">이 메뉴에 쓰지 않는 선택 재료: '+esc(x.unused.join(', '))+'</p>':'')+(x.r.id==='cockle-salad'?'<p class="note">꼬막은 손질하고 충분히 익힌 뒤 사용해요.</p>':'')+(x.r.external?'<p class="note">사용자 레시피의 재료 목록을 비교한 결과입니다. 정확한 분량은 상세 글을 확인하세요.</p>':'')+'<div class="card-actions"><a href="'+recipeUrl(x.r)+'">만드는 법 보기 →</a>'+(x.missing.length?'<button data-missing="'+i+'">부족한 재료 담기</button>':'')+'</div></div></article>').join('')||'<p>등록된 레시피 중 일치하는 재료가 없어요. 다른 재료를 추가해 보세요.</p>';}
function renderMemo(){if(!$('#shopping-list'))return;$('#shopping-list').innerHTML=memo.map((x,i)=>'<li><label><input type="checkbox" data-purchased="'+i+'" '+(x.purchased?'checked':'')+'> '+esc(x.name)+' <small>구매한 것 체크</small></label><button data-delete-memo="'+i+'" aria-label="'+esc(x.name)+' 삭제">×</button></li>').join('')||'<li>추천 메뉴에서 부족한 재료를 담아보세요.</li>';}
if($('#add-ingredient')){
 const params=new URLSearchParams(location.search);$('#kids-only').checked=params.get('kids')==='1';const current=recipes.find(r=>r.id===params.get('recipe'));if(current){$('#ingredient-input').placeholder=current.title+'에 쓸 재료를 선택하세요';}
 $('#add-ingredient').addEventListener('submit',e=>{e.preventDefault();addIngredient($('#ingredient-input').value);$('#ingredient-input').value='';});all('[data-add]').forEach(b=>b.addEventListener('click',()=>addIngredient(b.dataset.add)));all('[data-pantry]').forEach(b=>b.addEventListener('change',()=>{if(b.checked)pantry.add(b.dataset.pantry);else pantry.delete(b.dataset.pantry);if(lastResults.length)recommend()}));$('#recommend').addEventListener('click',recommend);$('#kids-only').addEventListener('change',()=>{if(selected.size)recommend()});
 document.addEventListener('click',e=>{const rm=e.target.closest('[data-remove]');if(rm){selected.delete(rm.dataset.remove);paintSelected();if(lastResults.length)recommend()}const b=e.target.closest('[data-missing]');if(b){const result=lastResults[Number(b.dataset.missing)];if(result){result.missing.forEach(x=>{if(!memo.some(m=>normal(m.name)===normal(x.name)))memo.push({name:x.name,purchased:false})});write('todaymeal-cooking-shopping-v1',memo);renderMemo();notice('장보기 메모에 담았어요.');}}const del=e.target.closest('[data-delete-memo]');if(del){memo.splice(Number(del.dataset.deleteMemo),1);write('todaymeal-cooking-shopping-v1',memo);renderMemo()}});
 $('#shopping-list').addEventListener('change',e=>{if(e.target.dataset.purchased===undefined)return;memo[Number(e.target.dataset.purchased)].purchased=e.target.checked;write('todaymeal-cooking-shopping-v1',memo)});
 $('#clear-purchased').addEventListener('click',()=>{memo=memo.filter(x=>!x.purchased);write('todaymeal-cooking-shopping-v1',memo);renderMemo()});$('#copy-shopping').addEventListener('click',async()=>{const text=memo.filter(x=>!x.purchased).map(x=>x.name).join('\n');if(!text)return notice('복사할 재료가 없어요.');try{await navigator.clipboard.writeText(text);notice('목록을 복사했어요.')}catch(e){const t=document.createElement('textarea');t.value=text;t.readOnly=true;$('#shopping').append(t);t.focus();t.select();notice('선택된 목록을 복사해 주세요.')}});paintSelected();renderMemo();if(selected.size)recommend();
 // Only recipes with an identifiable ingredient section are added. Never guess absent ingredients.
 const SB='https://jnwlaevfvhxpmmnkmyrw.supabase.co',KEY='sb_publishable_9yGKdu0Sh_hsboktuwYJhw_RQCu0W35';
 async function loadPublic(){try{let rows=[];for(let offset=0;offset<10000;offset+=100){const response=await fetch(SB+'/rest/v1/recipes?select=id,title,body,image_url&order=id.asc&limit=100&offset='+offset,{headers:{apikey:KEY,Authorization:'Bearer '+KEY},signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('fetch');const data=await response.json();if(!Array.isArray(data))throw Error('shape');rows.push(...data);if(data.length<100)break;}
 const extra=rows.map(r=>{const body=String(r.body||'');const m=body.match(/재료[^\n]*\n([\s\S]*?)(?:만드는\s*(?:법|방법)|조리\s*(?:법|방법|순서)|$)/);if(!m)return null;const lines=m[1].split(/\n|,/).map(x=>x.trim().replace(/^[^가-힣a-zA-Z]+/,'')).filter(x=>x&&x.length<100);const ingredients=lines.map(line=>({name:line.replace(/\([^)]*\)/g,'').split(/\d/)[0].replace(/\s*(약간|적당량|조금|소량).*$/,'').trim(),amount:''})).filter(x=>x.name&&x.name.length<25);if(!ingredients.length)return null;return {id:'public:'+r.id,sourceId:r.id,title:String(r.title||'레시피'),ingredients,external:true,photo:r.image_url};}).filter(Boolean);catalog.push(...extra);if(selected.size)recommend();}catch(e){notice('공개 레시피를 불러오지 못해 기본 요리 목록에서 추천합니다.')}}loadPublic();
}
window.addEventListener('storage',e=>{if(e.key===saveKey){const d=read(saveKey,[]);saved=new Set(Array.isArray(d)?d:[]);refreshSaves();savedPage();renderBasics()}});
refreshSaves();renderKids();renderBasics();savedPage();
})();
