'use strict';
window.createTodayMealEditor=function({sb,shrinkImage,mount,onSaved=()=>{}}){
const panel=document.createElement('section');
panel.innerHTML=`<style>
.factory-library{margin:22px 0;padding:18px;background:white;border:1px solid #e5ded5;border-radius:16px}.factory-library h2{font-size:18px;margin:0 0 10px}.factory-library p{font-size:14px;line-height:1.6}.factory-library button{padding:11px 14px;min-height:44px}.recipe-edit-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid #eee}.recipe-edit-row span{overflow-wrap:anywhere}.factory-library label{color:#343434;font-size:14px}.factory-library textarea{line-height:1.8;font-size:16px}.factory-library input{font-size:16px}.factory-library .edit-status{font-size:14px;line-height:1.6;color:#9b462a}.factory-library img{max-width:100%;max-height:280px;object-fit:contain;border-radius:12px}.factory-library [hidden]{display:none!important}
</style><div class="factory-library"><h2>내가 등록한 레시피</h2><p>등록한 글을 불러와 내용과 사진을 수정할 수 있습니다.</p><button type="button" id="edit-refresh">내 레시피 불러오기</button><div id="edit-list"></div><button type="button" id="edit-more" hidden>더 보기</button><p id="edit-list-status" role="status" aria-live="polite"></p>
<form id="recipe-editor" hidden><h2 tabindex="-1" id="edit-heading">레시피 수정</h2><label for="edit-title">제목</label><input id="edit-title" required maxlength="200"><label for="edit-body">레시피 내용</label><p>재료, 만드는 법, 요리 팁을 아래에서 직접 고쳐주세요.</p><textarea id="edit-body" rows="18" required></textarea><label for="edit-target">대상</label><input id="edit-target"><div class="row"><div><label for="edit-kcal">열량(kcal)</label><input id="edit-kcal" type="number" min="0"></div><div><label for="edit-carb">탄수화물(g)</label><input id="edit-carb" type="number" min="0" step="any"></div></div><div class="row"><div><label for="edit-protein">단백질(g)</label><input id="edit-protein" type="number" min="0" step="any"></div><div><label for="edit-fat">지방(g)</label><input id="edit-fat" type="number" min="0" step="any"></div></div><label for="edit-note">영양 설명</label><input id="edit-note"><label for="edit-photo">사진 교체</label><input id="edit-photo" type="file" accept="image/*"><p><img id="edit-preview" alt="레시피 사진 미리보기" hidden></p><button type="button" id="edit-remove-photo">사진 제거</button><p id="edit-photo-note"></p><label><input type="checkbox" id="edit-reviewed" style="width:auto">사진과 레시피가 맞는지 확인했습니다</label><p id="edit-status" class="edit-status" role="status" aria-live="polite"></p><button class="go" id="edit-save" type="submit">수정 내용 저장</button><button type="button" id="edit-cancel" style="margin-top:10px">수정 닫기</button></form></div>`;
mount.before(panel);panel.hidden=true;panel.className='explore-editor-panel';
const style=document.createElement('style');style.textContent=`.explore-editor-panel[hidden]{display:none!important}.explore-editor-panel .factory-library>h2,.explore-editor-panel .factory-library>p,.explore-editor-panel #edit-refresh,.explore-editor-panel #edit-more,.explore-editor-panel #edit-list{display:none}.explore-editor-panel #edit-list-status{display:block}.explore-editor-panel input,.explore-editor-panel textarea{box-sizing:border-box;width:100%;padding:12px;border:1px solid #ddd;border-radius:10px;font-family:inherit;background:white;color:#222}.explore-editor-panel label{display:block;margin:14px 0 6px}.explore-editor-panel .row{display:flex;gap:10px}.explore-editor-panel .row>div{flex:1;min-width:0}.explore-editor-panel #edit-save{display:block;width:100%;background:#c25a30;color:white;margin-top:12px}.explore-editor-panel #edit-heading{display:block}.explore-editor-panel #edit-reviewed{width:auto}`;panel.prepend(style);
const el=id=>panel.querySelector('#'+id);
const fields={title:'edit-title',body:'edit-body',target:'edit-target',kcal:'edit-kcal',carb:'edit-carb',protein:'edit-protein',fat:'edit-fat',nutri_note:'edit-note'};
let original=null,owner=null,offset=0,busy=false,dirty=false,newPhoto=null,imageUrl=null,objectUrl=null;
const status=t=>{el('edit-status').textContent=t;};
function lock(value){busy=value;panel.querySelectorAll('button,input,textarea').forEach(x=>x.disabled=value);}
function preview(url){if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null;}const img=el('edit-preview');img.hidden=!url;if(url)img.src=url;else img.removeAttribute('src');}
function closeEditor(){original=null;dirty=false;newPhoto=null;imageUrl=null;preview(null);el('recipe-editor').hidden=true;panel.hidden=true;}
function mayDiscard(){return !dirty||window.confirm('저장하지 않은 수정 내용이 있습니다. 닫을까요?');}
async function user(){if(!sb)throw new Error('로그인 모듈을 불러온 뒤 다시 시도해주세요.');const {data,error}=await sb.auth.getUser();if(error)throw error;if(!data?.user)throw new Error('로그인 후 이용해주세요.');return data.user;}
async function list(reset=true){if(busy)return;if(reset&&!mayDiscard())return;lock(true);el('edit-list-status').textContent='레시피를 불러오는 중…';try{
 const current=await user();if(reset||owner!==current.id){closeEditor();el('edit-list').replaceChildren();offset=0;owner=current.id;}
 const {data,error}=await sb.from('recipes').select('id,title').eq('user_id',owner).order('id',{ascending:false}).range(offset,offset+19);if(error)throw error;
 for(const row of data||[]){const item=document.createElement('div');item.className='recipe-edit-row';const name=document.createElement('span');name.textContent=row.title||'제목 없음';const button=document.createElement('button');button.type='button';button.textContent='수정';button.setAttribute('aria-label',(row.title||'레시피')+' 수정');button.onclick=()=>open(row.id);item.append(name,button);el('edit-list').append(item);}
 offset+=(data||[]).length;el('edit-more').hidden=(data||[]).length<20;el('edit-list-status').textContent=offset?'수정할 레시피를 선택해주세요.':'이 계정으로 등록한 레시피가 없습니다.';
 }catch(e){el('edit-list-status').textContent='불러오기 실패: '+e.message;}finally{lock(false);}}
async function open(id){if(busy||!mayDiscard())return;lock(true);try{const current=await user();if(current.id!==owner)throw new Error('로그인 계정이 바뀌었습니다. 목록을 다시 불러와주세요.');const {data,error}=await sb.from('recipes').select('*').eq('id',id).eq('user_id',current.id).single();if(error)throw error;original=data;newPhoto=null;imageUrl=data.image_url||null;for(const [key,input] of Object.entries(fields))el(input).value=data[key]??'';preview(imageUrl);el('edit-photo').value='';el('edit-reviewed').checked=false;el('edit-photo-note').textContent=imageUrl?'기존 사진입니다. 사진을 선택하지 않으면 그대로 유지됩니다.':'등록된 사진이 없습니다.';dirty=false;status('내용을 고친 뒤 수정 내용 저장을 눌러주세요.');el('recipe-editor').hidden=false;el('edit-heading').focus();el('edit-heading').scrollIntoView({block:'start',behavior:'smooth'});}catch(e){el('edit-list-status').textContent='불러오기 실패: '+e.message;}finally{lock(false);}}
function values(){const result={};for(const [key,input] of Object.entries(fields)){const value=el(input).value.trim();result[key]=['kcal','carb','protein','fat'].includes(key)?(value===''?null:Number(value)):value||null;}return result;}
async function save(event){event.preventDefault();if(busy||!original)return;const record=values();if(!record.title||!record.body)return status('제목과 레시피 내용을 입력해주세요.');if((imageUrl||newPhoto)&&!el('edit-reviewed').checked)return status('사진과 레시피를 확인한 뒤 확인 항목을 체크해주세요.');
 lock(true);status('수정 내용을 저장하는 중…');let uploadPath=null,saved=false;
 try{const current=await user();if(current.id!==original.user_id)throw new Error('등록한 계정으로 로그인해주세요.');
 record.image_url=imageUrl;
 if(newPhoto){uploadPath=current.id+'/'+crypto.randomUUID()+'.'+(newPhoto.type==='image/png'?'png':'jpg');const {error}=await sb.storage.from('photos').upload(uploadPath,newPhoto);if(error)throw error;record.image_url=sb.storage.from('photos').getPublicUrl(uploadPath).data.publicUrl;}
 const aiLine='사진: AI 생성 참고 이미지 (실제 촬영 사진 아님)';
 if((original.body||'').includes(aiLine)&&imageUrl&&!newPhoto&&!record.body.includes(aiLine))record.body+='\n\n'+aiLine;
 if(!record.image_url||newPhoto)record.body=record.body.replaceAll(aiLine,'').trim();
 let query=sb.from('recipes').update(record).eq('id',original.id).eq('user_id',current.id);
 for(const key of ['title','body','image_url','target','kcal','carb','protein','fat','nutri_note'])query=original[key]==null?query.is(key,null):query.eq(key,original[key]);
 const {data,error}=await query.select('id');if(error)throw error;if(!data?.length)throw new Error('수정 권한이 없거나 다른 창에서 내용이 변경되었습니다. 입력 내용은 유지됩니다. 기존 내용을 복사한 뒤 목록을 새로 불러와주세요.');
 saved=true;original={...original,...record};newPhoto=null;imageUrl=record.image_url;preview(imageUrl);el('edit-photo').value='';el('edit-body').value=record.body;dirty=false;status('수정 완료! 아래 탐색 목록에 반영되었습니다.');Promise.resolve().then(onSaved).catch(()=>status('저장은 완료됐지만 목록을 갱신하지 못했습니다. 새로고침해주세요.'));
 }catch(e){status('수정 실패: '+e.message);}
 finally{if(uploadPath&&!saved){try{await sb.storage.from('photos').remove([uploadPath]);}catch{}}lock(false);}}
el('edit-photo').onchange=async event=>{const file=event.target.files[0];if(!file||busy)return;if(file.size>25*1024*1024){status('25MB 이하 사진을 선택해주세요.');event.target.value='';return;}lock(true);let url;try{const compressed=await shrinkImage(file);url=URL.createObjectURL(compressed);const img=new Image();img.src=url;await img.decode();preview(null);objectUrl=url;el('edit-preview').src=url;el('edit-preview').hidden=false;newPhoto=compressed;el('edit-reviewed').checked=false;dirty=true;el('edit-photo-note').textContent='저장하면 이 사진으로 교체됩니다.';status('새 사진과 레시피를 확인해주세요.');}catch{if(url)URL.revokeObjectURL(url);status('사진을 읽지 못했습니다. JPG 또는 PNG로 다시 선택해주세요.');}finally{lock(false);}};
el('edit-remove-photo').onclick=()=>{if(busy)return;newPhoto=null;imageUrl=null;preview(null);el('edit-photo').value='';el('edit-reviewed').checked=false;dirty=true;el('edit-photo-note').textContent='저장하면 레시피에서 사진이 제거됩니다.';};
el('recipe-editor').addEventListener('input',event=>{dirty=true;if(event.target.id!=='edit-reviewed')el('edit-reviewed').checked=false;});
el('recipe-editor').onsubmit=save;el('edit-refresh').onclick=()=>list(true);el('edit-more').onclick=()=>list(false);el('edit-cancel').onclick=()=>{if(!busy&&mayDiscard())closeEditor();};window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
return {open:async id=>{if(busy)return;try{owner=(await user()).id;panel.hidden=false;await open(id);}catch(e){panel.hidden=false;el('edit-list-status').textContent=e.message;}},isDirty:()=>dirty};
};
